- name: micro service B configuration 
    hosts: all 
      become: yes
        become_user: root
        become_method: sudo
tasks:
        - name: get URL release
          get_url:
                 url: https://bootstrap.pypa.io/get-pip.py
                 dest: /tmp

        - name: Execute python script
          command: python /tmp/get-pip.py


        - name: get URL release
          get_url:
                  url: https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
                  dest: /tmp

        - name: Unarchive a files
          unarchive:
                 src: /tmp/consul_1.0.0_linux_amd64.zip
                 dest: /tmp

        - name: Move consul to bin
          command: mv /tmp/consul /usr/bin

        - file:
                path: /etc/consul.d
                state: directory
                mode: 0755
        - file:
                path: /etc/consul/data
                state: directory
                mode: 0755 
          


